nutriplans/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('', include('nutriplans_app.urls')),
    path('admin/', admin.site.urls),
]

nutriplans_app/urls.py
import django
from django.urls import path,include,re_path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name = 'signup'), 
    path('signin', views.signin, name = 'signin'), 
    path('logout', views.logout, name = 'logout'), 
    path('',include("django.contrib.auth.urls")), 
    path('workspace', views.workspace, name = 'workspace'), 
    path('client_page/<int:client_id>/', views.client_page, name = 'client_page'),
    path('client_page_new/<int:client_id>/', views.client_page_new, name = 'client_page_new'),
    path('create_plan/<int:client_id>/', views.create_plan, name = 'create_plan'),

    


]

nutriplans_app/models.py
import imp
from django.db import models
from django import forms
import datetime
from django.contrib.auth.models import User, Permission, Group

#nutrition_group, created = Group.objects.get_or_create(name="Nutrition")
#client_group, created = Group.objects.get_or_create(name="Client")

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
   

from six import text_type

class Clients(models.Model):
    status_choices = (
        ('Active', 'Active'),
        ('Active', 'Inactive'),
    )
    gender_choices = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(default='',max_length=32)
    status = models.CharField(max_length=7,choices=status_choices)
    gender= models.CharField(max_length=7,choices=gender_choices)
    birthday = models.CharField(default='',max_length=100)
    age = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    initial_weight = models.IntegerField(default=0)
    target_weight = models.IntegerField(default=0.0)
    email = models.EmailField(default='')
    phone = models.IntegerField(default=0)
    address = models.CharField(default='',max_length=100)
    notes = models.CharField(default='',max_length=1000)

    def __str__(self):
        return self.name



class Measurements(models.Model):
    client = models.ForeignKey(Clients, on_delete=models.CASCADE)
    date = models.CharField(default='',max_length=100)
    activity_factor = models.FloatField(default=1.0)
    weight = models.FloatField(default=0.0)
    fat= models.FloatField(default=0.0)
    muscle_mass = models.FloatField(default=0.0)
    bone_mass = models.FloatField(default=0.0)
    liquids = models.FloatField(default=0.0)
    vinceral_fat = models.FloatField(default=0.0)


    def __str__(self):
        return self.date




class Equivalents(models.Model):
    client = models.ForeignKey(Clients, on_delete=models.CASCADE)
    target_calories = models.FloatField(default=0.0)
    carbohydrates_percent = models.IntegerField(default=40)
    proteins_percent= models.IntegerField(default=30)
    fat_percent= models.IntegerField(default=30)
    full_milk = models.IntegerField(default=0)
    semi_milk = models.IntegerField(default=0)
    zero_milk = models.IntegerField(default=0)
    fruits = models.IntegerField(default=0)
    vegetables = models.IntegerField(default=0)
    bread_cereals = models.IntegerField(default=0)
    full_meat = models.IntegerField(default=0)
    semi_meat = models.IntegerField(default=0)
    zero_meat = models.IntegerField(default=0)
    fat = models.IntegerField(default=0)
    
    def __str__(self):
        return self.client

nutriplans_app/views.py
from functools import wraps
from pyexpat.errors import messages
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseForbidden
from nutriplans_app.forms import AddClients
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.models import User
from django.contrib import auth
from .forms import AddMeasurements, EditEquivalents, SignUpForm
from django.contrib import messages
from .models import Clients,Measurements,Equivalents
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.models import Group
from django.core import serializers
from django.conf import settings
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string 
from django.core.mail import EmailMultiAlternatives
from email.mime.image import MIMEImage
import os 
import time
import random
import constraint
from constraint import Problem

def group_required(*group_names):
    """Requires user membership in at least one of the groups passed in."""
    def in_groups(u):
        if u.is_authenticated:
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        return False

    return user_passes_test(in_groups, login_url='403')

def has_client(view):
    @wraps(view)
    def inner(request, client_id, *args, **kwargs):
        client = Clients.objects.all().filter(id=client_id)
        if client[0].user.id != request.user.id:
            return HttpResponseForbidden()
        return view(request, client_id, *args, **kwargs)
    return inner

def index(request):
    print(request.user)
    form = SignUpForm()
    return render(request, 'index.html',{'form': form})  


# Create your views here.

def signin(request):
    print( 'signin')
    if request.method == 'POST': 
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        print(user,username,password)
        if user is not None:
            login(request, user)
            if request.user.is_authenticated:
                print('is_authenticated')

                print()
                
                return redirect('workspace')
        else:
            return render(request, 'index.html',{'openmodal' : 'singin_modal','messages_signin':'username or password in wrong'}) 
    else:
         return render(request, 'index.html',{'openmodal' : 'singin_modal','messages_signin':'you must login first'}) 

def logout(request):
    print('logged out')
    auth.logout(request)

    return redirect('index')

        
# Create your views here.

@csrf_exempt
def signup(request):
    print('try signup')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():

            print('is valid')
            user = form.save()
            user.refresh_from_db()  
            # load the profile instance created by the signal
            user.save()
            raw_password = form.cleaned_data.get('password1')
 
            # login user after signing up
            user = authenticate(username=user.username, password=raw_password)
            nutrition_group = Group.objects.get(name='Nutrition') 
            nutrition_group.user_set.add(user)

            login(request, user)
 

            subject = 'welcome to GFG world'
            message = f'Hi {user.username}, thank you for registering in geeksforgeeks.'
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [user.email, ]

            # import html message.html file
            html_template = 'email_templates/singup_email.html'
            html_body = render_to_string(html_template, { 'username': user.username, })

            
            mail = EmailMultiAlternatives(
                subject, 'welcome to Nutritionist Plans', email_from, recipient_list)
            mail.attach_alternative(html_body, "text/html")


            try:
                mail.send()
            except:
                print(subject, message, email_from, recipient_list)
                print('ERROR not send email')
            # redirect user to home page
            return render(request, 'workspace.html',{'form': form})  
        else:
            openmodal='signup'
            return render(request, 'index.html',{'form': form, 'openmodal':openmodal}) 
    else:
        print('no valid')
        form = SignUpForm()
    return render(request, 'base.html', {'form': form})


@group_required('Nutrition')
@login_required(login_url='signin')
def workspace(request):

    print('\n--> workspace')
    if request.user.is_authenticated:

        #get user_id
        login_user_id=request.user.id
        print('\nlogin_user_id:',login_user_id)
        # get all clients from current user
        client_list = Clients.objects.all().filter(user_id=login_user_id)
        
        print(client_list)
        # get addpatientform
        add_client_form=AddClients()

        if request.method == 'POST':
            #add new client
            if request.POST.get('action_button')=='add_button':
                print('add client time')
                add_client_form = AddClients(request.POST)
                if add_client_form.is_valid():
                    print('time to save')
                    # load the profile instance created by the signal
                    name=request.POST['name']
                    status=request.POST['status']
                    gender=request.POST['gender']
                    birthday=request.POST['birthday']
                    age=request.POST['age']
                    height=request.POST['height']
                    target_weight=request.POST['target_weight']
                    email=request.POST['email']
                    phone=request.POST['phone']
                    address=request.POST['address']

                    new_client=Clients.objects.create(name=name,status=status,gender=gender,birthday=birthday, age=age, height=height,target_weight=target_weight,email=email,phone=phone,address=address,user_id=request.user.id )
                    new_client.save()
                    messages.success(request,''+name+' has been added! If you want to see ')

                    
                    # create equiv for new client
                    new_equiv = Equivalents(client_id=new_client.id,target_calories=0.0,carbohydrates_percent=40,proteins_percent=30,fat_percent=30,full_milk=0,semi_milk=0,zero_milk=0,fruits=0,vegetables=0,bread_cereals=0,full_meat=0,semi_meat=0,zero_meat=0,fat=0)
                    new_equiv.save()
                    
                    return render(request, 'workspace.html',{'client_list':client_list,'target_row':-1,'add_client_form':add_client_form})  

                else:
                    print('not valid')
                    openmodal='add_patient_modal'
                    return render(request, 'workspace.html',{'client_list':client_list,'target_row':-1,'add_client_form':add_client_form, 'openmodal':openmodal}) 

            if request.POST.get('action_button')=='view_client_page':
                #action="{% url 'client_page' field.user_id field.id %}"
                print ('redirect')
                target_client_id=request.POST['target_row']
                return redirect('client_page',client_id=target_client_id)

            if request.POST.get('action_button')=='delete_client':
                
                target_client_id=request.POST['target_row']
                print ('delete ',target_client_id)

                #get name fo delete client                
                target_client=Clients.objects.all().filter(id=target_client_id)
                target_client_name=target_client[0].name

                #delete target client
                Clients.objects.all().filter(id=target_client_id).delete()

                #get updated client list
                client_list = Clients.objects.all().filter(user_id=login_user_id)

                messages.success(request,''+target_client_name+' has been deleted!')

                return render(request, 'workspace.html',{'client_list':client_list,'add_client_form':add_client_form})
            
        else:
            return render(request, 'workspace.html',{'client_list':client_list,'add_client_form':add_client_form})  
    else:

        Sign_up_form = SignUpForm()
        
        return render(request, 'index.html',{'Sign_up_form': Sign_up_form, 'openmodal':'signin','messages_signin':'you must login first'}) 


@group_required('Nutrition')
@login_required(login_url='signin')
@has_client
def client_page(request, client_id):

    login_user_id=request.user.id
    print('id= ',client_id)
    target_client_id=client_id

    #get info client
    target_client = Clients.objects.all().filter(id=target_client_id)
    edit_client=AddClients(initial={'name':target_client[0].name,'status':target_client[0].status,'gender':target_client[0].gender,'birthday':target_client[0].birthday,'age':target_client[0].age,'height':target_client[0].height,'target_weight':target_client[0].target_weight,'email':target_client[0].email,'phone':target_client[0].phone,'address':target_client[0].address})

    client_measurements = Measurements.objects.all().order_by('-date').filter(client_id=target_client_id)
    add_measurment_form = AddMeasurements()


    client_equiv= Equivalents.objects.all().filter(client_id=client_id)
    print(client_id)

nutriplans_app/templates/base.html
<!doctype html>  
<html lang="en">  
  <head>  
    {% load static %}
    <!-- Required meta tags -->  
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}"/>
</head>  
  <body>  
  {% block content %}  
  <!------ Include the above in your HEAD tag ---------->
  
  <div id="navigation">
    <nav class="navbar navbar-expand-lg navbar-light ">
        <a class="navbar-brand" href="/">
            <img alt="home" src="{% static 'nutriplans_logo.png' %}" width="150" height="70">
        </a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
          
        {% if request.user.is_authenticated %}
            <div class="collapse navbar-collapse navigation_user" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto topnav">
                    <li class="nav-item active">
                        <a class="nav-link" style="color: white;" href="/workspace">Workspace</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="color: white;" href="#">Settings</a>
                    </li>
                </ul>
            </div>
        {%  endif %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto topnav">

                  <li class="nav-item">
                      <a class="nav-link" href="#">Υπηρεσίες</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">Πλάνα</a>
                  </li>

                  <!--
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Resources
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="#">Carfax</a>
                          <a class="dropdown-item" href="#">Carproof</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="#">Omnivic</a>
                      </div>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">About</a>
                  </li>
                  -->
                  <li class="nav-item">
                      <a class="nav-link" href="#">Contact</a>
                  </li>
                  {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link btn text-white" style="background-color: coral;" type="button" href="/logout">Logout</a>
                  </li>

                  {%  else %}
                  <li class="nav-item">
                    <a class="nav-link btn text-white" style="background-color: coral;" type="button" data-toggle="modal" data-target="#signup_modal">Sign up for free</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link btn text-black" style="background-color: white;" type="button" data-toggle="modal" data-target="#signin_modal">Sign in</a>

                      {% include "./modal_templates/sign.html" %}
                      {% include "./modal_templates/signup.html" %}
                  </li>
                  {% endif %}
                
                  

              </ul>
          </div>
      </nav> 
    </div>
    {% include "./help_templates/alert.html" %}
    {% endblock content %}  
  </body>  
</html>  


{% if openmodal == 'singin_modal' %}
<script>
  $('#signin_modal').modal('show');
</script>
{% endif %}

nutriplans_app/templates/client_base.html
<style>
   .layout_client_base {
    background-color: rgba(255, 127, 80, 0.2);
    width: 100%;
    display: flex;
    gap: 16px;
  } 
</style>


<section class="layout_client_base">
  <div class="btn" role="button" style="padding:5px; background-color:white; margin: 1%;">
        <i class="fa fa-user" style="font-size: 30px;" aria-hidden="true"></i>
        <h4>Client info</h4>
    </div>
    <div class="btn" role="button" style="padding:5px; background-color:white; margin: 1%;">
      <i class="fa fa-bar-chart" style="font-size: 30px;" aria-hidden="true"></i>
      <h4>Measurements</h4>
  </div>
  <div class="btn" role="button" style="padding:5px; background-color:white; margin: 1%;">
    <i class="fa fa-cutlery" style="font-size: 30px;" aria-hidden="true"></i>
    <h4>Meal plan</h4>
</div>
</section>

nutriplans_app/templates/client_page.html
<head>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/client_info_table.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/client_page.css' %}"/>

</head>
<style>


.layout {
  width: 100%;
  background-color: rgba(255, 127, 80, 0.2);
    min-height: 100%;
  display: grid;
  padding: 2%;
  grid:"column1 column2" 100%
    / 25% 75%;
  gap: 18px;

  align-content: start;
  align-items: start;
}

/* .layout {
  width: 100%;
  background-color: rgba(255, 127, 80, 0.2);
    min-height: 100%;
  display: grid;
  padding: 2%;
  grid:
  "header header header" auto
    ". body ." 100%
    "column1 column2" 100%
    / 25% 75%;
  gap: 18px;

  align-content: start;
  align-items: start;
} */


.column1 { grid-area: column1; }
.column2 { grid-area: column2; }

</style>

<body>
  <nav>
      {% include "./base.html" %}
  </nav>

  <section class="layout"> 
    <!-- <div class="header">
      {% include "./client_base.html" %}
    </div> -->
    <div class="column1 ">

      <h3>Client Information</h3>
          <table style="overflow-x:auto; width:100%" id="client_info_table1">
            {% for field in target_client %}
            <input type="hidden" name="target_row" value="{{field.id}}" >
            <tr>
              <th>Name</th>
              <td>{{ field.name }}</td>
            </tr>
            <tr>
              <th>Status</th>
              <td>{{ field.status }}</td>
            </tr>
            <tr>
              <th>Gender</th>
              <td id="id_gender">{{ field.gender }}</td>
            </tr>
            <tr>
              <th>Birthday</th>
              <td>{{ field.birthday }}</td>
            </tr>
            <tr>
              <th>Age</th>
              <td id="id_age">{{ field.age }}</td>
            </tr>
            <tr>
              <th>Height</th>
              <td id="id_height">{{ field.height }}</td>
            </tr>
            <tr>
              <th>Target Weight</th>
              <td>{{ field.target_weight }}</td>
            </tr>
            <tr>
              <th>Email</th>
              <td>{{ field.email }}</td>
            </tr>
            <tr>
              <th>Adress</th>
              <td>{{ field.address }}</td>
            </tr>
            {% endfor %}
          </table>
          <div class="submit_buttons" style="float: right; margin-top:2%;">
            <button class="btn btn-primary" style="background-color:coral; border-color:coral;" type="submit" name="action_button" value="edit_client_info" data-toggle="modal" data-target="#edit_client_modal"><i class="fa fa-edit"></i> Edit</button>
          </div>
          <h3>Create plan</h3>
          <div class="submit_buttons" style="float: left; margin-top:2%;">
            <form method="post">
              {% csrf_token %}
              <button class="btn btn-primary" style="background-color:coral; border-color:coral;" type="submit" name="action_button" value="create_plan"><i class="fa fa-building"></i> Create Plan</button>
            </form>
          </div>
      
    </div>

    <div class="column2">

        <h3>Equivalents</h3>
           <div class="row col-xs-6 col-md-12" style="margin-bottom:2%;">
            <div class="col-eqiv" style="width: 40%;">
              <table style="width:100%;">
            <tr>
              {% for field in client_equiv %}
              <tr>
                <th style="width: 12%;padding: 8px;"></th>
                <th style="width: 22%;padding: 8px;">Carbohydrates</th>
                <th style="width: 22%;padding: 8px;">Proteins</th>
                <th style="width: 22%;padding: 8px;">Fat</th>
                <th style="width: 22%;padding: 8px;">Calories</th>
              </tr>
              <tr>
                <th style="padding: 8px;">Targets</th>
                <td style="background-color: white;">{{field.carbohydrates_percent}} %</td>
                <td style="background-color: white;">{{field.proteins_percent}} %</td>
                <td style="background-color: white;">{{field.fat_percent}} %</td>
                <td style="background-color: white;">{{field.target_calories}} cal</td>
              </tr>
            
              <tr style="background-color: rgb(255, 230, 220);">
                <th style="padding: 8px;">Total (Gr)</th>
                <td id="total_gr_carbohydrates_cl"></td>
                <td  id="total_gr_proteins_cl"></td>
                <td  id="total_gr_fat_cl"></td>
                <td></td>
              </tr>
              <tr style="background-color: rgb(255, 176, 145);">
                <th style="padding: 8px;">Total (Cal)</th>

                <td id="total_cal_carbohydrates_cl"></td>
                <td id="total_cal_proteins_cl"></td>
                <td id="total_cal_fat_cl"></td>
                <td id="total_cal_cl"></td>
              </tr>
              <tr style="background-color: rgb(255, 230, 220);">
                <th style="padding:8px;">Percent (%)</th>
                <td  id="total_per_carbohydrates_cl"></td>
                <td id="total_per_proteins_cl"></td>
                <td id="total_per_fat_cl"></td>
                <td></td>
              </tr>
            
              {% endfor %}
            
            </tr>
              </table>
              <div class="submit_buttons" style="float: right; margin-top:2%;">
                <button type="button" class="btn btn-primary btn-md" style=" background-color: coral; border: 0;" data-toggle="modal" data-target="#edit_equivalents_modal" onclick="updateequiv();"> <i class="fa fa-edit"></i> Edit Equivalents
                </button>            
              </div>
            </div>
            <div class="col-eqiv" style=" width: 45%;">
              <canvas id="myChart1" style="width:100%;" ></canvas>

            </div>
            <div class="col-eqiv" style=" width: 15%;">
              <canvas id="myChart2"></canvas>

            </div>

        </div>
       


      {% include "./modal_templates/add_measurements_modal.html" %}
      {% include "./modal_templates/edit_measurements_modal.html" %}
      {% include "./modal_templates/edit_equivalents_modal.html" %}

      <div style="margin-bottom:2%;">
        <h3>Measurements</h3>
        <div class="tableWrap">
        <table class="table center" id="measurements_table" >
          <thead>
            <th>Date</th>
            <th>Activity Factor</th>
            <th>Weight</th>
            <th>Fat</th>
            <th>Muscle mass</th>
            <th>Bone mass</th>
            <th>Liguids</th>
            <th>Vinceral fat</th>
            <th>BMR</th>
            <th>BMI</th>
            <th>I.B.</th>
            <th></th>
            <th></th>

          </thead>
          <tbody style="margin:20px;">
            <tr>
              {% for field in client_measurements %}
                <tr>
                  <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="target_row" value="{{field.id}}" >
                    <td>{{field.date}}</td>
                    <td>{{field.activity_factor}}</td>
                    <td>{{field.weight}}</td>
                    <td>{{field.fat}}</td>
                    <td>{{field.muscle_mass}}</td>
                    <td>{{field.bone_mass}}</td>
                    <td>{{field.liquids}}</td>
                    <td>{{field.vinceral_fat}}</td>
                    <td id="bmr_{{field.id}}"></td>
                    <td id="bmi_{{field.id}}"></td>
                    <td id="ib_{{field.id}}" ></td>

                    <td> <button type="submit" style="background-color: transparent;" name="action_button" value="edit_measurements_button"><i class='fa fa-edit'></i></button> </td>
                    <td> <button type="submit" style="background-color: transparent;" name="action_button" value="delete_client_button"><i class='fa fa-trash'></i></button> </td>
                  </form>
                </tr>
              {% endfor %}   
          </tr>
          </tbody>
        </table>
        
        
        </div>
        <div class="submit_buttons" style="float: right;margin-bottom:2%;">
          <button type="button" class="btn btn-primary btn-md" style="margin:3%;width: 100%; background-color: coral; border: 0;" data-toggle="modal" data-target="#add_measurements_modal"> <i class="fa fa-plus"></i> Add Measurment
          </button>
        </div>
      </div>
      <h3>Diagrams</h3>
      <div class="row col-xs-6 col-md-12">

        <div class="col-chart" style="width:50%;">
          <canvas id="myChartweight" style="width:100%;"></canvas>
        </div>
        <div class="col-chart" style="width:50%;">
          <canvas id="myChart" style="width:100%;"></canvas>
        </div>
      </div>
    </div>
    
  </section>



  

  updateequiv

  {% if openmodal == 'add_measurements_modal' %}
  <script>
    $('#add_measurements_modal').modal('show');
  </script>
  {% endif %}
  {% if openmodal == 'edit_measurements_modal' %}
  <script>
    $('#edit_measurements_modal').modal('show');
  </script>
  {% endif %}
  {% if openmodal == 'edit_client_modal' %}
  <script>
    $('#edit_client_modal').modal('show');
  </script>
  {% endif %}
</body>

{% include "./help_templates/extra_calculations.html" %}  
{% include "./help_templates/chart_mesurements.html" %}
{% include "./help_templates/updateequiv.html" %}
{% include "./modal_templates/edit_client_modal.html" %}




  